slice_name: Snowflake | Query Date
description: null
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  datasource: 30__table
  viz_type: big_number_total
  slice_id: 168
  metric:
    aggregate: MAX
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: DATE
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 895
      is_certified: false
      is_dttm: true
      python_date_format: null
      type: DATE
      type_generic: 2
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: false
    label: MAX(DATE)
    optionName: metric_sv0w7b6efsg_amffkogfe3u
    sqlExpression: null
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: DATE
  header_font_size: 0.6
  subheader_font_size: 0.15
  y_axis_format: SMART_NUMBER
  time_format: '%Y-%m-%d'
  conditional_formatting: []
  extra_form_data: {}
  dashboards:
  - 12
query_context: '{"datasource":{"id":30,"type":"table"},"force":false,"queries":[{"filters":[{"col":"DATE","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":[],"metrics":[{"aggregate":"MAX","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"DATE","description":null,"expression":null,"filterable":true,"groupby":true,"id":895,"is_certified":false,"is_dttm":true,"python_date_format":null,"type":"DATE","type_generic":2,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"MAX(DATE)","optionName":"metric_sv0w7b6efsg_amffkogfe3u","sqlExpression":null}],"annotation_layers":[],"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{}}],"form_data":{"datasource":"30__table","viz_type":"big_number_total","slice_id":168,"metric":{"aggregate":"MAX","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"DATE","description":null,"expression":null,"filterable":true,"groupby":true,"id":895,"is_certified":false,"is_dttm":true,"python_date_format":null,"type":"DATE","type_generic":2,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"MAX(DATE)","optionName":"metric_sv0w7b6efsg_amffkogfe3u","sqlExpression":null},"adhoc_filters":[{"clause":"WHERE","comparator":"No
  filter","expressionType":"SIMPLE","operator":"TEMPORAL_RANGE","subject":"DATE"}],"header_font_size":0.6,"subheader_font_size":0.15,"y_axis_format":"SMART_NUMBER","time_format":"%Y-%m-%d","conditional_formatting":[],"extra_form_data":{},"dashboards":[12],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: d138c25f-944b-46a8-a142-bac455c86ae0
version: 1.0.0
dataset_uuid: d14836d8-c133-4406-82e5-0be45e265bed
