slice_name: Snowflake | Successful Queries
description: null
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  datasource: 30__table
  viz_type: big_number_total
  slice_id: 164
  metric:
    aggregate: SUM
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: IS_SUCCESSFUL
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 935
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: DECIMAL(1, 0)
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: false
    label: SUM(IS_SUCCESSFUL)
    optionName: metric_sv0w7b6efsg_amffkogfe3u
    sqlExpression: null
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: DATE
  header_font_size: 0.6
  subheader_font_size: 0.15
  y_axis_format: SMART_NUMBER
  time_format: smart_date
  conditional_formatting: []
  extra_form_data: {}
  dashboards:
  - 12
query_context: '{"datasource":{"id":30,"type":"table"},"force":false,"queries":[{"filters":[{"col":"DATE","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":[],"metrics":[{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"IS_SUCCESSFUL","description":null,"expression":null,"filterable":true,"groupby":true,"id":935,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"DECIMAL(1,
  0)","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"SUM(IS_SUCCESSFUL)","optionName":"metric_sv0w7b6efsg_amffkogfe3u","sqlExpression":null}],"annotation_layers":[],"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{}}],"form_data":{"datasource":"30__table","viz_type":"big_number_total","slice_id":164,"metric":{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"IS_SUCCESSFUL","description":null,"expression":null,"filterable":true,"groupby":true,"id":935,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"DECIMAL(1,
  0)","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"SUM(IS_SUCCESSFUL)","optionName":"metric_sv0w7b6efsg_amffkogfe3u","sqlExpression":null},"adhoc_filters":[{"clause":"WHERE","comparator":"No
  filter","expressionType":"SIMPLE","operator":"TEMPORAL_RANGE","subject":"DATE"}],"header_font_size":0.6,"subheader_font_size":0.15,"y_axis_format":"SMART_NUMBER","time_format":"smart_date","conditional_formatting":[],"extra_form_data":{},"dashboards":[12],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 557a8822-6793-4ee4-84c0-b81dda5b9ab5
version: 1.0.0
dataset_uuid: d14836d8-c133-4406-82e5-0be45e265bed
