slice_name: Platform | Snowpipe Files Count - Processed Daily
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_line
params:
  adhoc_filters:
  - clause: WHERE
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_qivk21nm30f_hf08i77mm54
    isExtra: false
    isNew: false
    operator: '!='
    operatorId: NOT_EQUALS
    sqlExpression: null
    subject: FILES_PROCESSED
  - clause: WHERE
    comparator: No filter
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_5c8wlqxikpx_6h4u7e1geth
    isExtra: true
    isNew: false
    operator: TEMPORAL_RANGE
    sqlExpression: null
    subject: LAST_LOAD_DATE
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    isExtra: true
    operator: TEMPORAL_RANGE
    subject: DATE
  annotation_layers: []
  color_scheme: googleCategory20c
  comparison_type: values
  dashboards:
  - 48
  datasource: 45__table
  extra_form_data: {}
  forecastInterval: 0.8
  forecastPeriods: 10
  groupby: []
  legendOrientation: top
  legendType: scroll
  markerSize: 6
  metrics:
  - aggregate: SUM
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: TOTAL_FILES_PROCESSED
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 2457
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: DECIMAL(18, 0)
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: true
    label: Files Processed
    optionName: metric_3fdzugp0h71_m9xosp927ad
    sqlExpression: null
  only_total: true
  opacity: 0.2
  rich_tooltip: true
  row_limit: 10000
  seriesType: line
  show_empty_columns: true
  show_legend: false
  slice_id: 428
  sort_series_type: sum
  tooltipTimeFormat: smart_date
  truncateXAxis: true
  truncate_metric: true
  viz_type: echarts_timeseries_line
  x_axis: DATE
  x_axis_time_format: smart_date
  x_axis_title_margin: 15
  y_axis_bounds:
  - null
  - null
  y_axis_format: SMART_NUMBER
  y_axis_title_margin: 15
  y_axis_title_position: Left
cache_timeout: null
uuid: 5bbe302e-e682-4b4b-b613-666bab008858
version: 1.0.0
dataset_uuid: 28908d7a-4d00-4747-a945-feee6679330f
