slice_name: Platform | Snowpipe Cost
description: null
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_pc0701l9ea_rss8b8phyyg
    isExtra: false
    isNew: false
    operator: TEMPORAL_RANGE
    operatorId: TEMPORAL_RANGE
    sqlExpression: null
    subject: DATE
  conditional_formatting: []
  dashboards:
  - 48
  datasource: 45__table
  extra_form_data: {}
  header_font_size: 0.3
  metric:
    aggregate: SUM
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: TOTAL_COST
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 2462
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: DECIMAL(38, 9)
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: false
    label: SUM(TOTAL_COST)
    optionName: metric_6xhkh3bzwmt_qhjgrts87h
    sqlExpression: null
  slice_id: 437
  subheader: ''
  subheader_font_size: 0.15
  time_format: smart_date
  viz_type: big_number_total
  y_axis_format: $,.2f
  annotation_layers: []
cache_timeout: null
uuid: e94a3054-587e-46cd-a6d2-627084503541
version: 1.0.0
dataset_uuid: 28908d7a-4d00-4747-a945-feee6679330f
